[package]
name = "free-download-netease-music"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
download_rs = "0.2.0"
clap = "2.33.3"
substring = "1.4.5"
